spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techchallenge
    username: "root"
    password: "m@_ssq@HJ7<h(+"
    driver-class-name: org.postgresql.Driver
mercadopago:
  access:
    token: SEU_ACCESS_TOKEN